### ISSUE TITLE
Ternary-Stream breaking on Node versions less than 6

### ISSUE THREAD

**Issue by grunj** [robrich/ternary-stream#12]
The latest dependency upgrade in the PR
https://github.com/robrich/ternary-stream/pull/11 is breaking on Node versions <6 (not supporting ES2015 syntax). 
I think @robrich has already addressed this here in the PR merge
_Originally posted by @robrich in https://github.com/robrich/ternary-stream/pull/11#issuecomment-512540816_

See if you can revert it and release it as a major version upgrade please.

**Comment by grunj** [comment]
Issue details:
`gulp-if(~2.0.1)` -> `ternary-stream` -> `merge-stream` -> `index.js:3`
(https://github.com/grncdr/merge-stream/blob/master/index.js#L3) is using es2015 syntax.
For builds on versions <6 this throws
`SyntaxError: Unexpected token {`

![Screenshot 2019-07-18 at 15 09 56](https://user-images.githubusercontent.com/30427910/61447266-3c057c80-a96e-11e9-85bb-cc53830e0a10.png)

**Comment by robrich** [comment]
Good catch. I need to patch upgrade dependencies back down, and major bump
for these dependencies. I mistakenly assumed officially supported node
versions were all I needed to worry about. Fail on me.

>

**Comment by robrich** [comment]
Published `2.1.1` that reverts the dependency version bumps so it'll work on node < 6.  For modern node, published `3.0.0`, and I'll update `gulp-if` in a minute.

**Comment by grunj** [comment]
Thanks for the quick turnaround.
