### ISSUE TITLE
Needs maintainers?

### ISSUE THREAD

**Issue by shinnn** [robrich/ternary-stream#8]
Currently this repo has some unreviewed (and important) PRs and open issues, but hasn't been updated for a long time.

@robrich I'd happily maintain this repo if you want to collaborate me.

**Comment by robrich** [comment]
I've been  hesitant to upgrade until I could repro and resolve https://github.com/robrich/gulp-if/issues/43 though in hind-sight, perhaps upgrading dependencies would resolve it.  I'll publish a new ternary-stream today.
